baseURL = "https://blog.christy.scot/"
languageCode = "en-us"
title = "Christy Codes"
theme = "hugo-theme-m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[params]
  author = "Christy Campbell"
  description = "website.start()"
  avatar = "https://avatars.githubusercontent.com/u/6845036?s=460&u=553e7df722c52b26858ea003e1ae3a13c6b84a47&v=4"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/christytc10"

[[params.social]]
  icon = "linkedin"
  name = "My Linkedin"
  url = "https://www.linkedin.com/in/christopher-campbell-aa1a3940/"

[[params.social]]
  icon = "message-square"
  name = "My Discord"
  url = "https://discord.com/users/Christy#2057"
